services:

  postgres-qa:
    image: postgres:15
    container_name: postgres-qa
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventario_db_qa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_qa_data:/var/lib/postgresql/data
    networks:
      - red-qa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventario_db_qa"]
      interval: 5s
      timeout: 5s
      retries: 10

  liquibase-qa:
    build: ../sistemas-distribuidos-bd
    container_name: liquibase-qa
    depends_on:
      postgres-qa:
        condition: service_healthy
    command: >
      --url=jdbc:postgresql://postgres-qa:5432/inventario_db_qa
      --username=admin
      --password=admin123
      --changeLogFile=changelog-master.xml
      update
    networks:
      - red-qa

  backend-autenticacion-qa:
    build: ../sistemas-distribuidos-backend-1
    container_name: backend-autenticacion-qa
    restart: unless-stopped
    ports:
      - "5010:5000"
    environment:
      SECRET_KEY: clave-qa
      DB_HOST: postgres-qa
      DB_PORT: 5432
      DB_NAME: inventario_db_qa
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      liquibase-qa:
        condition: service_completed_successfully
    networks:
      - red-qa

  backend-inventario-qa:
    build: ../sistemas-distribuidos-backend-2
    container_name: backend-inventario-qa
    restart: unless-stopped
    ports:
      - "5011:5001"
    environment:
      SECRET_KEY: clave-qa
      DB_HOST: postgres-qa
      DB_PORT: 5432
      DB_NAME: inventario_db_qa
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      liquibase-qa:
        condition: service_completed_successfully
    networks:
      - red-qa

  frontend-qa:
    build: ../sistemas-distribuidos-frontend
    container_name: frontend-qa
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.qa.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-autenticacion-qa
      - backend-inventario-qa
    networks:
      - red-qa

volumes:
  postgres_qa_data:

networks:
  red-qa:
    driver: bridge
